// <auto-generated />
using System;
using ComplyFlow.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComplyFlow.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225174839_AddRolesTable")]
    partial class AddRolesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComplyFlow.API.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Uyum Ekibi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "KVKK Kurulu"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hukuk Departmanı"
                        });
                });

            modelBuilder.Entity("ComplyFlow.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("ComplyFlow.API.Models.SubTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToGroupId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("SubTasks");
                });

            modelBuilder.Entity("ComplyFlow.API.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToGroupId");

                    b.HasIndex("AssignedToUserId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedToGroupId = 3,
                            AssignedToUserId = 1,
                            Description = "Yeni tedarikçi sözleşmesinin incelenmesi.",
                            DueDate = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Yüksek",
                            Status = "Beklemede",
                            TaskType = "",
                            Title = "Sözleşme İncelemesi"
                        },
                        new
                        {
                            Id = 2,
                            AssignedToGroupId = 2,
                            AssignedToUserId = 2,
                            Description = "Web sitesindeki aydınlatma metninin güncellenmesi.",
                            DueDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Orta",
                            Status = "Devam Ediyor",
                            TaskType = "",
                            Title = "KVKK Aydınlatma Metni Güncellemesi"
                        },
                        new
                        {
                            Id = 3,
                            AssignedToGroupId = 1,
                            Description = "Personel için yıllık uyum eğitimi sunumunun hazırlanması.",
                            DueDate = new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Düşük",
                            Status = "Tamamlandı",
                            TaskType = "",
                            Title = "Uyum Eğitimi Hazırlığı"
                        });
                });

            modelBuilder.Entity("ComplyFlow.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Ahmet Yılmaz",
                            PasswordHash = "",
                            Role = "Avukat",
                            Username = "ahmet.yilmaz"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Ayşe Demir",
                            PasswordHash = "",
                            Role = "Uyum Uzmanı",
                            Username = "ayse.demir"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Mehmet Kaya",
                            PasswordHash = "",
                            Role = "Stajyer",
                            Username = "mehmet.kaya"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Zeynep Çelik",
                            PasswordHash = "",
                            Role = "Yönetici",
                            Username = "zeynep.celik"
                        },
                        new
                        {
                            Id = 99,
                            FullName = "Master Admin",
                            PasswordHash = "$2a$11$JUUUdxfnetLG.uui3oh6/uSO14gjvzGp2Mv2Y8bLKg6fRD7Ll7UDC",
                            Role = "Admin",
                            Username = "administrator"
                        });
                });

            modelBuilder.Entity("ComplyFlow.API.Models.SubTask", b =>
                {
                    b.HasOne("ComplyFlow.API.Models.Group", "AssignedToGroup")
                        .WithMany()
                        .HasForeignKey("AssignedToGroupId");

                    b.HasOne("ComplyFlow.API.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId");

                    b.HasOne("ComplyFlow.API.Models.TaskItem", "TaskItem")
                        .WithMany("SubTasks")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToGroup");

                    b.Navigation("AssignedToUser");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("ComplyFlow.API.Models.TaskItem", b =>
                {
                    b.HasOne("ComplyFlow.API.Models.Group", "AssignedToGroup")
                        .WithMany()
                        .HasForeignKey("AssignedToGroupId");

                    b.HasOne("ComplyFlow.API.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId");

                    b.Navigation("AssignedToGroup");

                    b.Navigation("AssignedToUser");
                });

            modelBuilder.Entity("ComplyFlow.API.Models.TaskItem", b =>
                {
                    b.Navigation("SubTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
